import React from "react";
import { ArrowLeft, AlignLeft } from "lucide-react";

export default function Assumptions() {
  return (
    <div className="min-h-screen bg-slate-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto">
        <a href="/" className="inline-flex items-center text-sm font-medium text-indigo-600 hover:text-indigo-500 mb-8 transition-colors">
          <ArrowLeft className="w-4 h-4 mr-2" />
          Back to Calculator
        </a>
        
        <div className="bg-white rounded-3xl shadow-sm border border-slate-200 p-8 sm:p-12">
          <div className="flex items-center gap-4 mb-8 border-b border-slate-100 pb-8">
            <div className="w-12 h-12 bg-indigo-50 rounded-2xl flex items-center justify-center">
              <AlignLeft className="w-6 h-6 text-indigo-600" />
            </div>
            <div>
              <h1 className="text-3xl font-black text-slate-900 tracking-tight">Assumptions & Limitations</h1>
            </div>
          </div>

          <div className="prose prose-slate max-w-none">
            
            <p className="text-slate-600 leading-relaxed text-lg mb-8">
              All financial projections require making assumptions about an unpredictable future. WealthLens relies on several critical baseline assumptions that you should understand before utilizing our modeling tools.
            </p>

            <h2 className="text-xl font-bold text-slate-900 mt-8 mb-4">1. Constant Rate of Return</h2>
            <p className="text-slate-600 leading-relaxed mb-6">
              Our calculator assumes a linear, constant rate of return for the duration of the projection. In reality, financial markets (especially equities and crypto) are highly volatile. Returns will fluctuate yearly, monthly, and daily. A static 8% return assumption modeled over 20 years will yield a very different outcome than a real-world scenario of +20% one year and -10% the next, even if the average return over the 20 years is mathematically 8%. This phenomenon is known as sequence of returns risk.
            </p>

            <h2 className="text-xl font-bold text-slate-900 mt-8 mb-4">2. Reinvestment of Dividends</h2>
            <p className="text-slate-600 leading-relaxed mb-6">
              The calculations explicitly assume that any yield, interest, or dividends generated by the underlying assets are automatically and immediately reinvested back into the principal amount without incurring transaction fees or immediate tax liabilities, maximizing the compounding effect.
            </p>

            <h2 className="text-xl font-bold text-slate-900 mt-8 mb-4">3. Linear Inflation</h2>
            <p className="text-slate-600 leading-relaxed mb-6">
              Like returns, inflation is modeled as a constant, linear force dragging against the portfolio across the entire time horizon. Historically, inflation runs in short, unpredictable spikes and cycles.
            </p>

            <h2 className="text-xl font-bold text-slate-900 mt-8 mb-4">4. Simplified Tax Models</h2>
            <p className="text-slate-600 leading-relaxed mb-6">
              Our tax adjustment feature applies a flat, static rate against the total capital gains realized at the very end of the time horizon. It does not account for complex tax scenarios such as:
            </p>
            <ul className="list-disc pl-5 text-slate-600 mb-6 space-y-2">
              <li>Changing tax brackets throughout the projection period</li>
              <li>Differentiation between short-term vs long-term capital gains treatments</li>
              <li>Tax drag from dividend/interest distributions along the way</li>
              <li>State, local, or specialized wealth taxes depending on your absolute jurisdiction</li>
            </ul>

            <h2 className="text-xl font-bold text-slate-900 mt-8 mb-4">5. Currency Stability</h2>
            <p className="text-slate-600 leading-relaxed mb-6">
              Our currency selection tool purely formats the numeric output. It does not adjust the underlying growth assumptions for currency risk or foreign exchange rate fluctuations over the projected timeframe.
            </p>

          </div>
        </div>
      </div>
    </div>
  );
}
