import React from "react";
import { ArrowLeft, AlertTriangle } from "lucide-react";

export default function Disclaimer() {
  return (
    <div className="min-h-screen bg-slate-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto">
        <a href="/" className="inline-flex items-center text-sm font-medium text-indigo-600 hover:text-indigo-500 mb-8 transition-colors">
          <ArrowLeft className="w-4 h-4 mr-2" />
          Back to Calculator
        </a>
        
        <div className="bg-white rounded-3xl shadow-sm border border-slate-200 p-8 sm:p-12">
          <div className="flex items-center gap-4 mb-8 border-b border-slate-100 pb-8">
            <div className="w-12 h-12 bg-amber-50 rounded-2xl flex items-center justify-center">
              <AlertTriangle className="w-6 h-6 text-amber-600" />
            </div>
            <div>
              <h1 className="text-3xl font-black text-slate-900 tracking-tight">Financial Disclaimer</h1>
            </div>
          </div>

          <div className="prose prose-slate max-w-none">
            
            <div className="bg-amber-50 border-l-4 border-amber-500 p-6 rounded-r-xl mb-8">
                <p className="text-amber-900 font-bold m-0">
                  Past performance is not indicative of future results. All investing involves risk, including the possible loss of principal.
                </p>
            </div>

            <h2 className="text-xl font-bold text-slate-900 mt-8 mb-4">Educational Purposes Only</h2>
            <p className="text-slate-600 leading-relaxed mb-6">
              The information, calculations, and AI-generated insights provided by WealthLens are designed strictly for educational and informational purposes. This tool is not intended to provide specific financial, tax, or legal advice, nor is it a recommendation to buy or sell any specific securities or investment products.
            </p>

            <h2 className="text-xl font-bold text-slate-900 mt-8 mb-4">Accuracy of Projections</h2>
            <p className="text-slate-600 leading-relaxed mb-6">
              The projections generated by our calculators are hypothetical in nature and do not reflect actual investment results. They are based on the user's inputs—such as assumed rates of return, contributions, and inflation—which may vary significantly from real-world economic conditions. The calculations do not fully account for all possible fees, taxes, and transaction costs that could erode actual returns.
            </p>

            <h2 className="text-xl font-bold text-slate-900 mt-8 mb-4">Not Fiduciary Advice</h2>
            <p className="text-slate-600 leading-relaxed mb-6">
              WealthLens does not act in a fiduciary capacity for its users. Your use of this application does not create a client-advisor relationship. You should seek personalized advice from a qualified, licensed financial professional, accountant, or attorney regarding your unique situation before implementing any strategy discussed on this platform.
            </p>

            <h2 className="text-xl font-bold text-slate-900 mt-8 mb-4">No Liability</h2>
            <p className="text-slate-600 leading-relaxed mb-6">
              WealthLens bears no responsibility for any financial losses or damages incurred as a result of relying on the tools, calculators, or content provided on this website. You assume full responsibility for any investment decisions you make.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
